use_default_settings: true
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "ultrasecretkey" # Change this in production
search:
  safe_search: 0
  autocomplete: ""
engines:
  - name: google
    engine: google
    shortcut: g
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
ui:
  static_use_hash: true
